### ISSUE TITLE
Could not parse JSON error

### ISSUE THREAD

**Issue by baditaflorin** [mapbox/geojsonio-cli#11]
echo '[out:json];node(57.7,11.9,57.8,12.0)[amenity=bar];out;' | query-overpass | geojsonio

**Comment by tmcw** [comment]
What is query-overpass's output? If you run `echo '[out:json];node(57.7,11.9,57.8,12.0)[amenity=bar];out;' | query-overpass`. I would strongly wager that geojsonio-cli complains of invalid JSON because the JSON is invalid.

**Comment by tmcw** [comment]
Closing; no response. Most likely the JSON is invalid.
