### ISSUE TITLE
This geojson content cannot be opened in the browser, but can be interpreted when manually copied

### ISSUE THREAD

**Issue by CMCDragonkai** [mapbox/geojsonio-cli#17]
I tried it with:

```
geojsonio < /tmp/tree.txt
```

[tree.txt](https://github.com/mapbox/geojsonio-cli/files/732196/tree.txt)

It gives me a URL like:

```
http://geojson.io/#data=data:application/json,%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F2318390720%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A2318390720%2C%22tags%22%3A%7B%22access%22%3A%22private%22%2C%22amenity%22%3A%22bar%22%2C%22name%22%3A%22G%C3%B6teborgs%20vink%C3%A4llare%22%2C%22website%22%3A%22http%3A%2F%2Fwww.gbgvin.se%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.9643378%2C57.7064417%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F2468969556%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A2468969556%2C%22tags%22%3A%7B%22amenity%22%3A%22bar%22%2C%22name%22%3A%22Dancing%20Dingo%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.9767677%2C57.7002471%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F2468969615%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A2468969615%2C%22tags%22%3A%7B%22amenity%22%3A%22bar%22%2C%22name%22%3A%22Rockbaren%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.9765627%2C57.7001445%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F2749347064%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A2749347064%2C%22tags%22%3A%7B%22addr%3Acity%22%3A%22G%C3%B6teborg%22%2C%22addr%3Acountry%22%3A%22SE%22%2C%22addr%3Ahousenumber%22%3A%2227%22%2C%22addr%3Apostcode%22%3A%22416%2064%22%2C%22addr%3Astreet%22%3A%22Friggagatan%22%2C%22amenity%22%3A%22bar%22%2C%22name%22%3A%22%C3%96lstugan%20Tullen%22%2C%22opening_hours%22%3A%22Mo-Th%2016%3A00-01%3A00%3B%20Fr%2015%3A00-01%3A00%3B%20Sa-Su%2013%3A00-01%3A00%22%2C%22phone%22%3A%22%2B46%2031%2016%2056%2016%22%2C%22website%22%3A%22http%3A%2F%2Fwww.olstugan.se%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%
```

But copying in the content manually into geojson.io works and gives me a share URL like: http://bl.ocks.org/d/b6b589272ff838fd4c220a7fde473465

**Comment by tmcw** [comment]
Just downloaded the file and it produced

    http://geojson.io/#data=data:application/json,%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F2318390720%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A2318390720%2C%22tags%22%3A%7B%22access%22%3A%22private%22%2C%22amenity%22%3A%22bar%22%2C%22name%22%3A%22G%C3%B6teborgs%20vink%C3%A4llare%22%2C%22website%22%3A%22http%3A%2F%2Fwww.gbgvin.se%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.9643378%2C57.7064417%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F2468969556%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A2468969556%2C%22tags%22%3A%7B%22amenity%22%3A%22bar%22%2C%22name%22%3A%22Dancing%20Dingo%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.9767677%2C57.7002471%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F2468969615%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A2468969615%2C%22tags%22%3A%7B%22amenity%22%3A%22bar%22%2C%22name%22%3A%22Rockbaren%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.9765627%2C57.7001445%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F2749347064%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A2749347064%2C%22tags%22%3A%7B%22addr%3Acity%22%3A%22G%C3%B6teborg%22%2C%22addr%3Acountry%22%3A%22SE%22%2C%22addr%3Ahousenumber%22%3A%2227%22%2C%22addr%3Apostcode%22%3A%22416%2064%22%2C%22addr%3Astreet%22%3A%22Friggagatan%22%2C%22amenity%22%3A%22bar%22%2C%22name%22%3A%22%C3%96lstugan%20Tullen%22%2C%22opening_hours%22%3A%22Mo-Th%2016%3A00-01%3A00%3B%20Fr%2015%3A00-01%3A00%3B%20Sa-Su%2013%3A00-01%3A00%22%2C%22phone%22%3A%22%2B46%2031%2016%2056%2016%22%2C%22website%22%3A%22http%3A%2F%2Fwww.olstugan.se%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.9909991%2C57.7125346%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F3183389861%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A3183389861%2C%22tags%22%3A%7B%22amenity%22%3A%22bar%22%2C%22name%22%3A%22Cristal%20Bar%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.972163%2C57.709277%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F3212503161%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A3212503161%2C%22tags%22%3A%7B%22amenity%22%3A%22bar%22%2C%22name%22%3A%22Basque%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.961811%2C57.704539%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F3593394528%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A3593394528%2C%22tags%22%3A%7B%22addr%3Acity%22%3A%22G%C3%B6teborg%22%2C%22addr%3Acountry%22%3A%22SE%22%2C%22addr%3Ahousenumber%22%3A%228%22%2C%22addr%3Apostcode%22%3A%2241120%22%2C%22addr%3Astreet%22%3A%22Rosenlundsgatan%22%2C%22amenity%22%3A%22bar%22%2C%22name%22%3A%22Boulebar%22%2C%22opening_hours%22%3A%22Mo-Th%2016%3A00-23%3A00%3B%20Fr%2015%3A00-24%3A00%3B%20Sa%2000%3A00-01%3A00%2C10%3A00-24%3A00%3B%20Su%2000%3A00-01%3A00%2C10%3A00-22%3A00%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.9587861%2C57.7011491%5D%7D%7D%2C%7B%22type%22%3A%22Feature%22%2C%22id%22%3A%22node%2F3819446557%22%2C%22properties%22%3A%7B%22type%22%3A%22node%22%2C%22id%22%3A3819446557%2C%22tags%22%3A%7B%22amenity%22%3A%22bar%22%2C%22name%22%3A%22Pix%20%26%20Pintxos%20Cocktails%22%7D%2C%22relations%22%3A%5B%5D%2C%22meta%22%3A%7B%7D%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B11.965178%2C57.70257%5D%7D%7D%5D%7D

Maybe try updating geojsonio-cli?

**Comment by CMCDragonkai** [comment]
I'm on 0.2.1, this is running on Windows node 7.3.0.

**Comment by tmcw** [comment]
Unfortunately can't replicate this issue locally. Please update if you see another way to debug this.
