### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by omidfi** [mapbox/geojsonio-cli#9]
Hi, 
I read the docs, but I just don't get it! 
I have a local geojson file, and it's 2 mb in size, trying to load it on geojson.io fails with 
no latlang object

error. So I installed this cli tool. It runs and exites without any errors, but where are my data going? 

   geojsonio < shops.geojson

**Comment by omidfi** [comment]
Ok, now I see. I got the link using --print
But still, it says sorry some errors occured. 

What is the file size limit for geojsonio? I have 15k features with one property on each.

**Comment by omidfi** [comment]
Do you mind if I add some explanations to readme? 
I think this is supposed to open the browser to the url, but it doesn't for me. It might happen to others as well.

**Comment by tmcw** [comment]
Sure, would happily accept a PR improving the readme.

**Comment by tmcw** [comment]
Closing; PR accepted.
